### ISSUE TITLE
why should I set json_path_train and json_path_valid in the config file

### ISSUE THREAD

**Issue by LXYTSOS** [baidu-research/NCRF#15]
Since we've already know which part is tumor and which is normal(PATCHES_TUMOR_TRAIN and PATCHES_NORMAL_TRAIN), why should I still provide the json formatted annotations when training?

**Comment by yil8** [comment]
@LXYTSOS Because for each coordinate, we sampled a 768x768 patch and then further split it into a grid of 3x3 256x256 patches. Only the label of the center coordinate of the 3x3 grid is known, the labels of the other 8 surroundings are still unknown and need to be retrieved through the json annotation.

**Comment by LXYTSOS** [comment]
thanks a lot, I just figured that out today by reading the training code.
