### ISSUE TITLE
The idea about Pathological section

### ISSUE THREAD

**Issue by mooncakehe** [baidu-research/NCRF#3]
I see you use 3x3 patches as the input. how about 5x5 or 7x7?
I kown the neighboring patch is also important to classify.
but Pathological classify has Histology and cytology. if the problem is cytology. will this skill work?

**Comment by yil8** [comment]
@mooncakehe Yes, you can definitely use 5x5 or 7x7, and the current codebase already supports this. But during training, you have to further reduce batch size to make sure memory fits. The only overhead is when you compute the probability map, there is going to be more computation wasted, since the current implementation is a little bit stupid.... Right now, only the prediction of the center patch is retained, so 3x3 means 8 times computation wasted, and I don't want to think about the case for 5x5 or 7x7. 

For cytology, I don't have quite much experiences. But if that roughly means classifying cell types, I would think it requires smaller patch size (around the size of cells maybe). The CRF smoothing should still be helpful though, since the spatial structure of cells seems rich.
