### ISSUE TITLE
mask of Test_026 inference stride 

### ISSUE THREAD

**Issue by yingdiLee** [baidu-research/NCRF#33]
In Tissue mask part, you said you generate the mask of Test_026.tif in level 6 corresponding to the inference stride of 64, but I found the level 6 downsample factor is 57.375,  dose it means the inference stride is nearly 57 instead of 64?

**Comment by yil8** [comment]
@yingdiLee How did you find the level 6 downsample factor is 57.375?

**Comment by yingdiLee** [comment]
this is my code:
import openslide
    wsi = openslide.OpenSlide('/open405/zyd/CAMELYON16/testing/images/test_026.tif')
    print(wsi.level_downsamples)

and I got this:
 /home/zyd/anaconda3/bin/python /home/zyd/PycharmProjects/Camelyon16/wsi/tissue_mask.py
(1.0, 1.9950980392156863, 3.9901960784313726, 7.903846153846153, 15.807692307692307, 30.5, 57.375, 98.75, 197.5)

Process finished with exit code 0
The level6 downsample factor is 57.375

**Comment by yil8** [comment]
@yingdiLee Can you print the wsi.level_dimensions ? I remember they are powers of 2

**Comment by mahendrakhened** [comment]
The wsi.level_dimensions are not in powers of 2. 
Take for example: Test_001.tif
Number of Levels: 9
Dimensions:(86016, 89600), level_dimensions:((86016, 89600), (43008, 45056), (21504, 22528), (10752, 11264), (5632, 5632), (3072, 3072), (1536, 1536), (1024, 1024), (512, 512)).

Also, in the inference code: wsi_producer.py -> GridWSIPatchDataset() -> lines-> 54- 65, execution fails.
So, I had to comment the below lines to run the inference. How were you able to run the inference code? Since the images are not in powers of 2, won't there be an incorrect mapping from the level-6 image points to level-0 patches? 
        X_slide, Y_slide = self._slide.level_dimensions[0]
        X_mask, Y_mask = self._mask.shape

        # if X_slide / X_mask != Y_slide / Y_mask:
        #     raise Exception('Slide/Mask dimension does not match ,'
        #                     ' X_slide / X_mask : {} / {},'
        #                     ' Y_slide / Y_mask : {} / {}'
        #                     .format(X_slide, X_mask, Y_slide, Y_mask))

        self._resolution = X_slide * 1.0 / X_mask
        # if not np.log2(self._resolution).is_integer():
        #     raise Exception('Resolution (X_slide / X_mask) is not power of 2 :'
        #                     ' {}'.format(self._resolution))

        # all the indices for tissue region from the tissue mask

**Comment by yil8** [comment]
@mahendrakhened I guess you are running into the same error as #6 , can you take a look?
